name: Build

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-files-bot:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Логин в реестр контейнеров
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 3: Извлечение метаданных для Docker (теги, лейблы)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Шаг 4: Строим и пушим Docker образ, используя Dockerfile из папки .docker/
      - name: Build and push Docker image from .docker/Dockerfile
        uses: docker/build-push-action@v5.3.0
        with:
          context: .  # Контекст сборки — это весь репозиторий
          file: .docker/Dockerfile  # Путь к Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
